<<<<<<< HEAD
# Generated by Django 3.2.16 on 2022-12-18 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.16 on 2022-12-18 13:14

from django.db import migrations, models
>>>>>>> refs/remotes/origin/main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> refs/remotes/origin/main
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=250)),
                ('website_blocked', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.CharField(max_length=255)),
>>>>>>> refs/remotes/origin/main
            ],
        ),
    ]
