# Generated by Django 3.2.16 on 2022-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(max_length=4)),
                ('usage', models.IntegerField()),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
    ]
