# Generated by Django 3.2.16 on 2022-12-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_durationusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availaible_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availaible_ip', models.IntegerField(max_length=12)),
            ],
        ),
    ]
