# Generated by Django 3.2.16 on 2022-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_availaible_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availaible_ip',
            name='Availaible_ip',
            field=models.CharField(max_length=255),
        ),
    ]
