# Generated by Django 3.2.16 on 2022-12-24 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_logs_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_generated',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 20, 39, 29, 59380)),
        ),
    ]
