# Generated by Django 3.2.16 on 2022-12-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_logs_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_generated',
            name='date',
            field=models.CharField(default='15:42:59', max_length=255),
        ),
    ]
