# Generated by Django 3.2.16 on 2022-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_logs_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_generated',
            name='date',
            field=models.CharField(default='19:49:17', max_length=255),
        ),
    ]
